require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.6.5
  NewCops: enable
  Exclude:
    - Gemfile

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LeadingEmptyLines:
  Enabled: false
